apiVersion: v1
kind: DeploymentConfig
metadata:
  creationTimestamp: null
  generation: 1
  name: {{ .Release.Name }}-jenkins
  namespace: {{ .Release.Namespace }}
spec:
  minReadySeconds: 60
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 2
  selector:
    name: {{ .Release.Name }}-jenkins
  strategy:
    activeDeadlineSeconds: 21600
    recreateParams:
      timeoutSeconds: 600
    resources: {}
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: {{ .Release.Name }}-jenkins
    spec:
      containers:
      - env:
        - name: TZ
          value: America/Argentina/Buenos_Aires   
        - name: JENKINS_HOME
          value: /var/jenkins_home/jenkins/jenkins_home
        image: jenkinsci/blueocean:1.18.0
        imagePullPolicy: Always
        name: {{ .Release.Name }}-jenkins
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8443
          protocol: TCP
        - containerPort: 50000
          protocol: TCP
        resources:
          limits:
            memory: 2Gi
          requests:
            memory: 1Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/jenkins_home
          name: vol-jenkins-home
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: sa-{{ .Release.Name }}
      serviceAccountName: sa-{{ .Release.Name }}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: vol-jenkins-home
        emptyDir: {}
      initContainers:
      - command:
        - sh
        - -c
        - |
          git clone https://bitbucket.org/crowdarautomation/lippia-web-example-project.git /var/jenkins_home;
          chown 1000:1000 -R /var/jenkins_home
        image: alpine/git
        imagePullPolicy: Always
        name: clone-repo
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/jenkins_home
          name: vol-jenkins-home 
  test: false
  triggers:
  - type: ConfigChange
---  
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    name: {{ .Release.Name }}-jenkins
  name: {{ .Release.Name }}-jenkins
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: "8080"
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: "8443"
    port: 8443
    protocol: TCP
    targetPort: 8443
  - name: "50000"
    port: 50000
    protocol: TCP
    targetPort: 50000
  selector:
    name: {{ .Release.Name }}-jenkins
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Route
metadata:
  annotations:
    openshift.io/host.generated: "true"
  creationTimestamp: null
  labels:
    name: {{ .Release.Name }}-jenkins
  name: {{ .Release.Name }}-jenkins
  namespace: {{ .Release.Namespace }}
spec:
  port:
    targetPort: "8080"
  to:
    kind: Service
    name: {{ .Release.Name }}-jenkins
    weight: 100
  wildcardPolicy: None
