version: "3.3"
services:
  zalenium:
    image: "dosel/zalenium"
    container_name: selenium-grid_web-sample
    hostname: selenium-grid_web-sample
    tty: true
    volumes:
      - /tmp/videos:/home/seluser/videos
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    ports:
      - 4444:4444
    environment:
      - PULL_SELENIUM_IMAGE=true
      - TZ=America/Argentina/Buenos_Aires
    command: >
      start --desiredContainers 1
            --maxDockerSeleniumContainers 10
            --timeZone "America/Argentina/Buenos_Aires"

  jenkins_web-sample:
    image: jenkins/jenkins:lts
    privileged: true
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - ./docker/jenkins_home:/var/jenkins_home

  nginx_web-sample:
    image: nginx:stable
    volumes:
      - ./docker/jenkins_home/reportsVolume:/usr/share/nginx/html
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8081:80
    environment:
      - TZ=America/Argentina/Buenos_Aires
